@startuml dd_sequence_diagram_accident_collector
skinparam Shadowing false

participant ":AccidentDataCollector" as ADC
participant ":MunicipalityAPIWrapper" as MAPIW
participant ":SuggestionsEngine" as SE
participant ":DBMS" as DBMS

loop When scheduled

ADC -> ADC : collectMunicipalityUpdates(name)
activate ADC
ADC -> DBMS : selectMunicipality(name)
activate DBMS
DBMS --> ADC : municipality
deactivate DBMS
ADC -> MAPIW : requestAccidents\n(municipality.name, municipality.lastCollected)
activate MAPIW
MAPIW --> ADC : newAccidents
deactivate MAPIW
ADC -> DBMS : insertAccidents(municipality, newAccidents)
activate DBMS
DBMS --> ADC : success
deactivate DBMS
deactivate ADC
end

loop When scheduled
SE -> DBMS : selectMunicipality(name)
activate SE
activate DBMS
DBMS --> SE : municipality
deactivate DBMS
SE -> SE : checkUpdates(municipality)
alt There are new violations or accidents
SE -> SE : newSuggestions =\nrunMachineLearning(municipality)
SE -> DBMS : insertSuggestions(newSuggestions)
activate DBMS
DBMS --> SE : success
deactivate DBMS
deactivate SE
end
end
@enduml