@startuml dd_sequence_diagram_uc_2_3
skinparam Shadowing false

actor Authority as A
participant ":AuthorityWebApp" as AWA
participant ":WebServer" as WS
participant ":Router" as R
participant ":SuggestionsManager" as SM
participant ":DBMS" as DBMS

A -> AWA : requestSuggestionsPage()
activate AWA
AWA -> WS : retrieveStaticContent()
activate WS
WS --> AWA : staticContent
deactivate WS
AWA -> R : requestAvailableSuggestions()
activate R
R -> SM : requestAvailableSuggestions()
activate SM
SM -> SM : retrieveAvailableSuggestions()
note right
    The SuggestionsManager identifies
    the Authority from it's session
    token, so that it can apply
    the required filters to show
    it only their suggestions
end note
activate SM #e8e8e8
SM -> DBMS : executeQuery(query)
activate DBMS
DBMS --> SM : queryResults
deactivate SM
alt There are no Suggestions to be shown
SM --> AWA : noSuggestionsAvailable
AWA --> A : noSuggestionsAvailable
else There are Suggestions to be shown
SM --> AWA : availableSuggestions
AWA --> A : suggestionsPage
A -> AWA : requestDetails(sug)
AWA -> R : requestSuggestionDetails(sug)
R -> SM : requestSuggestionDetails(sug)
SM -> SM : retrieveDetails(sug)
activate SM #e8e8e8
SM -> DBMS : executeQuery(query)
DBMS --> SM : queryResults
deactivate SM
SM --> AWA : suggestionDetails
AWA --> A : detailsPage
alt Authority carries out the suggestion
A -> AWA : markAsCarriedOut(sug)
AWA -> R : markSuggestionAsCarriedOut(sug)
R -> SM : markAsCarriedOut(sug)
deactivate R
SM -> SM : markAsCarriedOut(sug)
SM -> DBMS : executeQuery(query)
DBMS --> SM : queryResult
deactivate DBMS
SM --> AWA : success
deactivate SM
AWA --> A : operationSuccess
deactivate AWA
end
end




@enduml