@startuml dd_sequence_diagram_uc_1_4
skinparam Shadowing false

actor User as U
participant ":UserMobileApp" as UMA
participant ":Router" as R
participant ":StatisticsEngine" as SE
participant ":StatisticsRepresentationManager" as SRM
participant ":DBMS" as DBMS

U -> UMA : selectStatisticsPage()
activate UMA
UMA -> UMA : location = getCurrentLocation()
UMA -> R : requestAvailableStatisticsTypes(location)
activate R
R -> SE : requestAvailableStatisticsTypes(location)
activate SE
SE -> SE : checkAvailableStatistics(location)
activate SE #e8e8e8
SE -> DBMS : selectViolations(query)
activate DBMS
DBMS --> SE : queryResults
deactivate SE
alt There are no available statistics
SE --> UMA : noStatisticsAvailableError
UMA --> U : noStatisticsAvailable
else
SE --> UMA : availableTypes
UMA --> U : statisticsTypesPage
U -> UMA : selectType(type)
UMA -> R : requestStatistics(type,filters,MOBILE)
R -> SE : requestStatistics(type,filters,MOBILE)
deactivate R
SE -> SE : fetchStatistics(type,filters)
activate SE #e8e8e8
SE -> DBMS : selectViolations(query)
DBMS --> SE : queryResults
deactivate DBMS
deactivate SE
SE -> SRM : formatStatisticsData(type,queryResults,MOBILE)
activate SRM
SRM -> SRM : generateLabels(type,queryResults)
SRM -> SRM : generateColors(type,queryResults)
SRM -> SRM : applyFormat(MOBILE)
SRM --> SE : formattedStatistics
deactivate SRM
SE --> UMA : formattedStatistics
deactivate SE
UMA -> UMA : renderStatistics(formattedStatistics)
UMA --> U : visualizeData
deactivate UMA
end

@enduml