@startuml rasd_sequence_diagram_uc_1_2
skinparam Shadowing false

actor User as U
participant SafeStreets as SS

U -> SS : loginRequest(req)
SS -> SS : checkInsertedData(req)

alt username and password do not match
SS --> U : error
else 
SS --> U : loginSuccessful
end

@enduml