@startuml rasd_sequence_diagram_uc_2_3
skinparam Shadowing false

actor Authority as A
participant SafeStreets as SS

A -> SS : requestAvailableSuggestions()
SS -> SS : retrieveSuggestions(auth)
alt there are available suggestions
SS --> A : availableSuggestions
A -> SS : requestDetails(sug)
SS -> SS : collectData(sug)
SS --> A : suggestionDetails
alt suggestion carried out 
A -> SS : markAsCarriedOut(sug)
SS -> SS : markAsCarriedOut(sug)
SS --> A : confirmation
end
else
SS --> A : noSuggestionsAvailable
end


@enduml