@startuml rasd_sequence_diagram_uc_1_4
skinparam Shadowing false

actor User as U
participant SafeStreets as SS

U -> SS : requestStatisticsType()
alt there are available statistics
SS --> U : availableStatistics
U -> SS : requestSpecificStatistics(stat)
SS -> SS : elaborateData()
SS --> U : statisticsData
else
SS --> U : showWarning
end

@enduml