@startuml rasd_sequence_diagram_uc_1_4
skinparam Shadowing false

actor User as U
participant SafeStreets as SS

U -> SS : requestStatisticsType(type)
alt there are available statistics
SS --> U : availableStatistics
U -> SS : filterStatistics(filter)
SS -> SS : elaborateData(stats, filter)
SS --> U : statisticsData
else
SS --> U : noStatisticsAvailable
end

@enduml