@startuml rasd_sequence_diagram_uc_1_1
skinparam Shadowing false

actor User as U
participant SafeStreets as SS

U -> SS : registrationRequest(req)

SS -> SS : checkFiscalCodeFormat(fisc)
alt invalid fiscal code format
SS --> U : showWarning
else
SS -> SS : checkUniqueIdentifiers(id)
alt username or fiscal code already in use
SS --> U : showWarning
else
SS -> SS: registerUser(usr)
SS --> U: successfulRegistration
end
end

@enduml