@startuml rasd_sequence_diagram_uc_2_1
skinparam Shadowing false

actor Authority as A
participant SafeStreets as SS

A -> SS : requestViolationsReports(auth)
SS -> SS : retrieveViolationReports(auth)
alt some reports are available to be reviewed
SS --> A : violationReportList
A -> SS : selectViolation(rep)
SS --> A : availableActions
A -> SS : selectAction(action)
SS -> SS : applyAction(rep, action)
SS --> A : actionSuccess
else
SS --> A : violationReportsAlreadyReviewed
end

@enduml