@startuml rasd_sequence_diagram_uc_1_1
skinparam Shadowing false

actor User as U
participant SafeStreets as SS

U -> SS : registrationRequest(req)

SS -> SS : checkFiscalCodeFormat\n(req.fiscalCode)
alt invalid fiscal code format
SS --> U : warning
else
SS -> SS : checkUniqueIdentifiers\n(req.fiscalCode, req.username)
alt username or fiscal code already in use
SS --> U : warning
else
SS -> SS: registerUser(req)
SS --> U: successfulRegistration
end
end

@enduml