@startuml rasd_sequence_diagram_uc_2_2
skinparam Shadowing false

actor Authority as A
participant SafeStreets as SS

A -> SS : requestStatisticsType(type)
alt there are available statistics
SS --> A : availableStatistics
A -> SS : filterStatistics(filter)
SS -> SS : elaborateData(stats, filter)
SS --> A : statisticsData
else
SS --> A : noStatisticsAvailable
end

@enduml