@startuml
left to right direction

[*] --> PendingViolation

PendingViolation --> AcceptedViolation : authority:Accept
PendingViolation --> DiscardedViolation : authority:Discard

AcceptedViolation --> [*]
DiscardedViolation --> [*]

@enduml